"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.flags = exports.actionInfo = exports.__updateEntityBasedOnWhere = exports.getEntitySettings = exports.fieldOptionsEnricher = exports.getControllerRef = exports.controllerRefImpl = exports.decorateColumnSettings = exports.getRelationFieldInfo = exports.getRelationInfo = exports.sqlRelationsFilter = exports.sqlRelations = void 0;
var remult_static_js_1 = require("./src/remult-static.js");
var sql_relations_js_1 = require("./src/data-providers/sql-relations.js");
Object.defineProperty(exports, "sqlRelations", { enumerable: true, get: function () { return sql_relations_js_1.sqlRelations; } });
Object.defineProperty(exports, "sqlRelationsFilter", { enumerable: true, get: function () { return sql_relations_js_1.sqlRelationsFilter; } });
var relationInfoMember_js_1 = require("./src/remult3/relationInfoMember.js");
Object.defineProperty(exports, "getRelationInfo", { enumerable: true, get: function () { return relationInfoMember_js_1.getRelationInfo; } });
Object.defineProperty(exports, "getRelationFieldInfo", { enumerable: true, get: function () { return relationInfoMember_js_1.getRelationFieldInfo; } });
var RepositoryImplementation_js_1 = require("./src/remult3/RepositoryImplementation.js");
Object.defineProperty(exports, "decorateColumnSettings", { enumerable: true, get: function () { return RepositoryImplementation_js_1.decorateColumnSettings; } });
Object.defineProperty(exports, "controllerRefImpl", { enumerable: true, get: function () { return RepositoryImplementation_js_1.controllerRefImpl; } });
Object.defineProperty(exports, "getControllerRef", { enumerable: true, get: function () { return RepositoryImplementation_js_1.getControllerRef; } });
Object.defineProperty(exports, "fieldOptionsEnricher", { enumerable: true, get: function () { return RepositoryImplementation_js_1.fieldOptionsEnricher; } });
var getEntityRef_js_1 = require("./src/remult3/getEntityRef.js");
Object.defineProperty(exports, "getEntitySettings", { enumerable: true, get: function () { return getEntityRef_js_1.getEntitySettings; } });
var filter_interfaces_js_1 = require("./src/filter/filter-interfaces.js");
Object.defineProperty(exports, "__updateEntityBasedOnWhere", { enumerable: true, get: function () { return filter_interfaces_js_1.__updateEntityBasedOnWhere; } });
exports.actionInfo = remult_static_js_1.remultStatic.actionInfo;
var remult3_js_1 = require("./src/remult3/remult3.js");
Object.defineProperty(exports, "flags", { enumerable: true, get: function () { return remult3_js_1.flags; } });
